apiVersion: v1
kind: Pod
metadata:
  name: cic-vpx
  labels:
    app: cic-vpx
spec: 
      serviceAccountName: frontenddeveloper-cpx
      containers:
      - name: cic-vpx
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.7.6"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
         - name: "NS_IP"
           value: "192.168.1.180"
         # Set username for Nitro
         # Set log level
         - name: "NS_ENABLE_MONITORING"
           value: "YES"
         - name: "NS_APPS_NAME_PREFIX"
           value: "frontend"
         - name: "NS_USER"
           value: "CIC"
         - name: "NS_PASSWORD"
           value: "8675309"
         - name: "NAMESPACE"
           value: "frontend-developers"
         - name: "EULA"
           value: "yes"
         - name: "LOGLEVEL"
           value: "DEBUG"
        args:
          - --ingress-classes
            vpx-frontend
          - --feature-node-watch
            true
        imagePullPolicy: IfNotPresent
